### ISSUE TITLE
Unable to start the application 

### ISSUE THREAD

**Issue by BilalBudhani** [bigbinary/aceinvoice-distribution#5]
Just downloaded the latest release for Mac but couldn't get it working. A screenshot is attached below

<img width="782" alt="Screenshot 2020-03-28 at 7 27 34 PM" src="https://user-images.githubusercontent.com/1650995/77824642-3df12380-712a-11ea-96ea-c9d1dae9d857.png">

Model: Macbook Pro 16 inch (2019 model)
OS: 10.15.3 (19D76)

**Comment by neerajsingh0101** [comment]
@BilalBudhani Sorry about that. We'll look into it.

**Comment by muhsin-k** [comment]
@BilalBudhani We are sorry about this issue. We have tested using **16” Mac Pro** laptop and it is working perfectly.

![photo6082634905273084616](https://user-images.githubusercontent.com/12408980/78749591-2ddc0e00-798c-11ea-8ab5-1de40dcb9327.jpg)

Could you please try once more using the version from [AceInvoice](https://www.aceinvoice.com/download)?

**Comment by BilalBudhani** [comment]
@muhzi4u Thank you for looking into this. Yes, dmg from the link you mentioned above is working. I was facing issue when I downloaded it from `releases` of this repo.

**Comment by muhsin-k** [comment]
@BilalBudhani Great. We will upload the latest version soon.
